import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import ReduxProvider from "@/redux/provider/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary min-h-screen flex flex-col`}
      >
        <ReduxProvider>
          <Header />
          <main className="flex-grow max-w-[80rem] mx-auto w-full">
            {children}
          </main>
          <Footer />
          <Toaster position="top-center" />
        </ReduxProvider>
      </body>
    </html>
  );
}
